# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItem, QStandardItemModel

class Ui_Analysis(object):
    def setupUi(self, Analysis):
        Analysis.setObjectName("Analysis")
        Analysis.resize(570, 567)
        self.tableView = QtWidgets.QTableView(Analysis)
        self.tableView.setGeometry(QtCore.QRect(10, 90, 551, 411))
        self.tableView.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.tableView.setObjectName("tableView")
        self.comboBox = QtWidgets.QComboBox(Analysis)
        self.comboBox.setGeometry(QtCore.QRect(140, 20, 131, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(179, 179, 179);\n"
"font: 16pt \"黑体\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["工作阶段", "职业", "性别", "地域"])
        self.label = QtWidgets.QLabel(Analysis)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 16pt \"黑体\";")
        self.label.setObjectName("label")
        self.RunAnalysis = QtWidgets.QPushButton(Analysis)
        self.RunAnalysis.setGeometry(QtCore.QRect(280, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(24)
        self.RunAnalysis.setFont(font)
        self.RunAnalysis.setStyleSheet("border-image: url(:/imagees/pic10.png);")
        self.RunAnalysis.setText("")
        self.RunAnalysis.setObjectName("RunAnalysis")
        self.graphicsView = QtWidgets.QGraphicsView(Analysis)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 571, 571))
        self.graphicsView.setStyleSheet("border-image: url(:/imagees/background3.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.tableView.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        self.RunAnalysis.raise_()

        self.retranslateUi(Analysis)
        self.RunAnalysis.clicked.connect(self.OnRunAnalysis) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Analysis)

    def retranslateUi(self, AnalysisWnd):
        _translate = QtCore.QCoreApplication.translate
        AnalysisWnd.setWindowTitle(_translate("AnalysisWnd", "统计分析"))
        self.label.setText(_translate("AnalysisWnd",
        "<html><head/><body><p><span style=\" color:#c7b420;\">分析维度：</span></p></body></html>"))
    def OnRunAnalysis(self):
        print('启动分析')
        from GlobalVariable import global_obj
        init_weight = global_obj.InitWeight
        sel = self.comboBox.currentIndex()
        row = 10
        if sel == 0:
            self.model_analysis = QStandardItemModel(10, 5)
            self.model_analysis.setHorizontalHeaderLabels(['小学生', '初中生', '高中生', '大学生', '已参加工作'])
            vl = init_weight.weight1
            col = 5

        elif sel == 1:
            self.model_analysis = QStandardItemModel(10, 6)
            self.model_analysis.setHorizontalHeaderLabels(['老师', '学生', '程序员', '工程师', '网络主播', '其他'])
            vl = init_weight.weight3
            col = 6

        elif sel == 2:
            self.model_analysis = QStandardItemModel(10, 2)
            self.model_analysis.setHorizontalHeaderLabels(['男', '女'])
            vl = init_weight.weight2
            col = 2


        elif sel == 3:
            self.model_analysis = QStandardItemModel(10, 2)
            self.model_analysis.setHorizontalHeaderLabels(['南方', '北方'])
            vl = init_weight.weight4
            col = 2

        else:
            print('fatal failed')
            return

        # 添加数据到TableView中
        self.model_analysis.setVerticalHeaderLabels(['电视', '电影', '鬼畜', '生活', '时尚', '数码', '舞蹈', '音乐', '游戏', '娱乐'])
        for i in range(row):
            for j in range(col):
                self.model_analysis.setItem(i, j, QStandardItem(str(vl[i][j])))

        self.tableView.setModel(self.model_analysis)


import pic_rc
