# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(591, 591)
        self.Comment = QtWidgets.QLabel(Welcome)
        self.Comment.setGeometry(QtCore.QRect(70, 530, 421, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Comment.setFont(font)
        self.Comment.setObjectName("Comment")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Welcome)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 581, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(43, 16777215, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Title = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Title.setMaximumSize(QtCore.QSize(441, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.horizontalLayout.addWidget(self.Title)
        spacerItem1 = QtWidgets.QSpacerItem(81, 16777215, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.graphicsView = QtWidgets.QGraphicsView(Welcome)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 591, 591))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.graphicsView.setFont(font)
        self.graphicsView.setStyleSheet("border-image: url(:/imagees/background3.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Welcome)
        self.label.setGeometry(QtCore.QRect(240, 560, 71, 21))
        self.label.setObjectName("label")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Welcome)
        self.graphicsView_2.setGeometry(QtCore.QRect(180, 190, 256, 261))
        self.graphicsView_2.setStyleSheet("border-image: url(:/imagees/pic1.png);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView.raise_()
        self.Comment.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label.raise_()
        self.graphicsView_2.raise_()

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "欢迎页"))
        self.Comment.setWhatsThis(_translate("Welcome", "<html><head/><body><p><span style=\" font-weight:600;\">q</span></p></body></html>"))
        self.Comment.setText(_translate("Welcome", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#cacaca;\">核心数据加载中</span></p></body></html>"))
        self.Title.setText(_translate("Welcome", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#919148;\">短视频推荐系统</span></p></body></html>"))
        self.label.setText(_translate("Welcome", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#e3e3e3;\">请稍候</span></p></body></html>"))
import pic_rc
