# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QGraphicsPixmapItem, QGraphicsScene


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(698, 463)
        self.textBrowser = QtWidgets.QTextBrowser(Welcome)
        self.textBrowser.setGeometry(QtCore.QRect(5, 271, 681, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar = QtWidgets.QProgressBar(Welcome)
        self.progressBar.setGeometry(QtCore.QRect(7, 420, 721, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setMaximum(0)
        self.progressBar.setMinimum(0)
        self.label = QtWidgets.QLabel(Welcome)
        self.label.setGeometry(QtCore.QRect(10, 0, 681, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Welcome)
        self.label_2.setGeometry(QtCore.QRect(310, 50, 71, 41))
        self.label_2.setObjectName("label_2")
        self.graphicsView = QtWidgets.QGraphicsView(Welcome)
        self.graphicsView.setGeometry(QtCore.QRect(260, 90, 181, 181))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Welcome)
        self.graphicsView_2.setGeometry(QtCore.QRect(40, 90, 181, 181))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Welcome)
        self.graphicsView_3.setGeometry(QtCore.QRect(480, 90, 181, 181))
        self.graphicsView_3.setObjectName("graphicsView_3")
        frame = QImage("core_developer.jpg")
        pix = QPixmap.fromImage(frame)
        item = QGraphicsPixmapItem(pix)
        scene = QGraphicsScene()
        scene.addItem(item)
        self.graphicsView.setScene(scene)

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "欢迎页"))
        self.label.setText(_translate("Welcome", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">欢迎使用短视频推荐模拟系统</span><span style=\" font-size:20pt; font-style:italic; vertical-align:sub;\">v 1.0</span></p></body></html>"))
        self.label_2.setText(_translate("Welcome", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">开发者：</span></p></body></html>"))
